### ISSUE TITLE
Testing and optimisation for ARTIC V4 primers

### ISSUE THREAD

**Issue by mattdmem** [sheffield-bioinformatics-core/periscope#21]
V4 primer sets and reference files we need to include

https://github.com/artic-network/artic-ncov2019/tree/master/primer_schemes/nCoV-2019/V4

We need some test data - but good to add all reference files and options to periscope:
- primer bed
- amplicon bed
- option in code to choose V4

**Comment by mbdabrowska1** [comment]
- [x] Add artic_primers_V4.bed file
- [x] Add artic_amplicons_V4.bed file
- [x] Add an option to pick V4 primers when running periscope
