### ISSUE TITLE
Add 1.2kb midnight primers

### ISSUE THREAD

**Issue by mattdmem** [sheffield-bioinformatics-core/periscope#26]
This fork has added the new nanopore primers which are a different scheme to the artic ones we currently user: https://github.com/aicbu/periscope

Might be good to implement this? Maybe contact the fork owner and ask them to make a pull request?

**Comment by mbdabrowska1** [comment]
- [x] merge forked repo into new branch midnight
- [x] add options to specify custom primer and amplicon files
- [x] provide description on what are the requirements for custom primer and amplicon files
