### ISSUE TITLE
error “one of the commands exited with non-zero exit code; note: snakemake uses bash strict mode"

### ISSUE THREAD

**Issue by quangu0925** [sheffield-bioinformatics-core/periscope#37]
I ran periscope on Illumina RNA-Seq data to detect sgRNA counts (without amplicons)
However, I have the error on the last step:
My command:
**periscope -t 16 --fastq /SARS2samples/input.fastq   --technology illumina --output-prefix 40_C1 —-resources ./periscope/resources --sample 40_C1**

I have the error:

**Error in rule periscope:
    jobid: 3
    output: 40_C1_periscope_counts.csv, 40_C1_periscope_amplicons.csv, 40_C1_periscope_novel_counts.csv
    shell:
        python /home4/gugu01q/miniconda3/envs/periscope/lib/python3.6/site-packages/periscope/scripts/search_for_sgRNA_illumina.py --bam 40_C1.bam --score-cutoff 50 --output-prefix 40_C1 --score-cutoff 50 --sample 40_C1 --orf-bed ./periscope/resources/orf_start.bed --primer-bed ./periscope/resources/artic_primers_V1.bed --amplicon-bed ./periscope/resources/artic_amplicons_V1.bed --tmp /tmp --threads 16
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message**

Could you help me to solve it?

Thank you!

**Comment by quangu0925** [comment]
Sorry I forgot to paste the full error:

**python /home4/gugu01q/miniconda3/envs/periscope/lib/python3.6/site-packages/periscope/scripts/search_for_sgRNA_illumina.py --bam 40_C1.bam --score-cutoff 50 --output-prefix 40_C1 --score-cutoff 50 --sample 40_C1 --orf-bed ./periscope/resources/orf_start.bed --primer-bed ./periscope/resources/artic_primers_V1.bed --amplicon-bed ./periscope/resources/artic_amplicons_V1.bed --tmp /tmp --threads 16
Traceback (most recent call last):
  File "/home4/gugu01q/miniconda3/envs/periscope/lib/python3.6/site-packages/periscope/scripts/search_for_sgRNA_illumina.py", line 5, in <module>
    import pysam
  File "/home4/gugu01q/RSeQC/usr/local/lib/python2.7/dist-packages/pysam/__init__.py", line 1, in <module>
    from pysam.csamtools import *
ImportError: /home4/gugu01q/RSeQC/usr/local/lib/python2.7/dist-packages/pysam/csamtools.so: undefined symbol: _Py_ZeroStruct
[Tue Nov  9 22:10:39 2021]
Error in rule periscope:
    jobid: 3
    output: 40_C1_periscope_counts.csv, 40_C1_periscope_amplicons.csv, 40_C1_periscope_novel_counts.csv
    shell:
        python /home4/gugu01q/miniconda3/envs/periscope/lib/python3.6/site-packages/periscope/scripts/search_for_sgRNA_illumina.py --bam 40_C1.bam --score-cutoff 50 --output-prefix 40_C1 --score-cutoff 50 --sample 40_C1 --orf-bed ./periscope/resources/orf_start.bed --primer-bed ./periscope/resources/artic_primers_V1.bed --amplicon-bed ./periscope/resources/artic_amplicons_V1.bed --tmp /tmp --threads 16
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)**

**Comment by mbdabrowska1** [comment]
> **Error in rule periscope: jobid: 3 output: 40_C1_periscope_counts.csv, 40_C1_periscope_amplicons.csv, 40_C1_periscope_novel_counts.csv shell: python /home4/gugu01q/miniconda3/envs/periscope/lib/python3.6/site-packages/periscope/scripts/search_for_sgRNA_illumina.py --bam 40_C1.bam --score-cutoff 50 --output-prefix 40_C1 --score-cutoff 50 --sample 40_C1 --orf-bed ./periscope/resources/orf_start.bed --primer-bed ./periscope/resources/artic_primers_V1.bed --amplicon-bed ./periscope/resources/artic_amplicons_V1.bed --tmp /tmp --threads 16 (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!) Shutting down, this might take some time. Exiting because a job execution failed. Look above for error message**

Is this the full error? I think there should be more information on the type of error that occurred. It's difficult for me to diagnose what the problem is with just this bit.

**Comment by quangu0925** [comment]
Hi Magda
I have solved the issue.  Thank you all the same.
by the way, I ask a naive question.
On the ./periscope/resource/orf_start.bed, what is the start and end of the
orf?

MN908947.3      20      40      ORF1a

MN908947.3      21532   21572   S

MN908947.3      25361   25401   ORF3a

MN908947.3      26213   26253   E


If you go to NCBI, e,g. https://www.ncbi.nlm.nih.gov/nuccore/MN908947.3
e.g. gene S is from 21563 to 25384.
Is this sth else?

Thank you!
Best,
Quan

**Comment by quangu0925** [comment]
I have solved the installation of the periscope issue.  Thank you very much!.
by the way, I ask a very naive question.
If you go to NCBI, e,g. https://www.ncbi.nlm.nih.gov/nuccore/MN908947.3
e.g. gene S is from 21563 to 25384, gene ORF3a is from 25393 to 26220.
That is the whole gene.

On the ./periscope/resource/orf_start.bed, what is the start and end of the orf?
MN908947.3      20      40      ORF1a
MN908947.3      21532   21572   S
MN908947.3      25361   25401   ORF3a
MN908947.3      26213   26253   E

Thank you!

**Comment by mbdabrowska1** [comment]
> On the ./periscope/resource/orf_start.bed, what is the start and end of the orf?

The orf_start.bed file each row is a range around the ORF start site. This means that this range is a buffer that includes the actual start site of the gene I believe. @mattdmem might know more about why its the exact numbers that are being used?

**Comment by DrownedMala** [comment]
> I have solved the installation of the periscope issue. Thank you very much!. by the way, I ask a very naive question. If you go to NCBI, e,g. https://www.ncbi.nlm.nih.gov/nuccore/MN908947.3 e.g. gene S is from 21563 to 25384, gene ORF3a is from 25393 to 26220. That is the whole gene.
> 
> On the ./periscope/resource/orf_start.bed, what is the start and end of the orf? MN908947.3 20 40 ORF1a MN908947.3 21532 21572 S MN908947.3 25361 25401 ORF3a MN908947.3 26213 26253 E
> 
> Thank you!

Could you kindly explain how you solved it? 
Thanks in advance,
Simone

**Comment by mattdmem** [comment]
> > On the ./periscope/resource/orf_start.bed, what is the start and end of the orf?
> 
> The orf_start.bed file each row is a range around the ORF start site. This means that this range is a buffer that includes the actual start site of the gene I believe. @mattdmem might know more about why its the exact numbers that are being used?

Yes this is correct - it's the region periscope uses to assign the sgRNA to that ORF. It's the TRS site with a bit of a buffer!
