### ISSUE TITLE
Error while running periscope

### ISSUE THREAD

**Issue by DrownedMala** [sheffield-bioinformatics-core/periscope#38]
Hello, 
We installed periscope as advised on the github page and installation ended with no errors.
We ran periscope with the following command:
`periscope --fastq 9083_1A/9083-1A.R1.fastq.gz 9083_1A/9083-1A.R2.fastq.gz --output-prefix test --artic-primers V3 -t 30 -mp 30 -r /home/lucam/periscope/periscope/resources --sample 9083_1A --technology illumina`
but we get an error and cannot solve it.

Here's the log file:
[2021-11-18T155404.621774.snakemake.log](https://github.com/sheffield-bioinformatics-core/periscope/files/7564025/2021-11-18T155404.621774.snakemake.log)

Has anyone any idea on how to solve this?
Thanks a lot,
Simone

**Comment by mbdabrowska1** [comment]
How does the terminal output look like when it errors out? It could be due to python trying to open too many processes (30), I'd try running it with 6-8 threads and seeing it that helps in this situation. How big is the fastq you're trying to run (roughly how many reads) ?
