### ISSUE TITLE
Generate same ONT statistics for Illumina data

### ISSUE THREAD

**Issue by Liukvr** [sheffield-bioinformatics-core/periscope#41]
Dear Periscope developers,

thanks for the great tool. We are using Periscope with Illumina data (Artic V3 amplicon sequenced 2x250bp). The generated output file fields are reported below

```
Illumina data:
sample,mapped_reads,orf,sgRNA_count,coverage,sgRPTL,sgRPHT
```

While when using ONT data the software generates more information:

 ```
ONT data
sample,orf,mapped_reads,amplicons,gRNA_count,nsgRNA_HQ_count,nsgRNA_LQ_count,gRHPT,nsgRPTg_HQ,nsgRPTg_LQ,nsgRPTg_ALL,nsgRPHT_HQ,nsgRPHT_LQ,nsgRPHT_ALL
```

It would be possible to generate the same ONT statistics (e.g. amplicons and gRNA_count) using the Illumina data? 

Thanks in advance for your support,
Luca Marcolungo

**Comment by mattdmem** [comment]
Hi Luca,

So the way they work is a bit different. For Illumina we don't really think about amplicons, what we normalise to is the coverage around the TRS site. The reason we did this was because Illumina data comes in different flavours, from amplicon to capture etc so our choice here was to produce something that would be a catch all.  We could probably output genome RNA counts though! @mbdabrowska1 what do you think?

Matt

**Comment by Liukvr** [comment]
Hi Matt, 
Thanks for the reply. Did you have the chance to check if it would be possible to have the RNA counts?
Thanks,
Luca

**Comment by mbdabrowska1** [comment]
Hi, good idea, I will look into adding that

**Comment by Liukvr** [comment]
Hi @mbdabrowska1, 
thanks for looking into that. Is it already planned the release of the new software version including those new features?
Thanksa in adavnce,
Luca

**Comment by Liukvr** [comment]
Hi @mbdabrowska1 @mattdmem,
do you have any update about this?
Best regards,
Luca

**Comment by mbdabrowska1** [comment]
Hi @Liukvr, I'm a little bit busy with a different project at the minute, but I will have a look at implementing those new features early next week. Sorry for the delay.

**Comment by Liukvr** [comment]
Hi @mbdabrowska1, many thanks for the update!

**Comment by mbdabrowska1** [comment]
@Liukvr I have added gRNA counts per ORF to Illumina datasets. Hope this helps. Note however that these gRNA counts are calculated differently than the ones in Nanopore datasets. Here they are counted as gRNA per ORF rather than per amplicon.

**Comment by DrownedMala** [comment]
Thanks for the added feature! 
Just one more thing: 
for sgRNA you select reads with a soft-clipped region at the 5' end and align it to the leader sequence, assigning that read as a sgRNA if length and quality of alignment against the leader seq. are good enough.
Could you explain how gRNAs are counted instead? Is every read that falls inside an ORF while not being assigned as sgRNA classified as a gRNA?

Thanks in advance,
Simone.

**Comment by mbdabrowska1** [comment]
Yes that's right. If a read is assigned an ORF but it doesn't align to the leader sequence it is labelled as gRNA
