### ISSUE TITLE
KeyError: 'ORF7a', Illumina reads

### ISSUE THREAD

**Issue by DrownedMala** [sheffield-bioinformatics-core/periscope#44]
Hello dear developers,
since illumina's gRNA count-version was released, we tested it and got the error below from some samples.
We are running periscope on data coming from duplicates, and it's returning this error only for one replicate at a time, while the other one runs flawlessly.
Also, the same samples analyzed before this update ran without any issue; here I post the terminal's error output and, below that, the message contained in the snakemake.log.

Do you have any suggestion/idea about the nature of these errors? 
Thanks again for your tool and support!
Simone

### Terminal's:
```
Traceback (most recent call last):
  File "/home/malago/miniconda3/envs/periscope/lib/python3.6/site-packages/periscope/scripts/search_for_sgRNA_illumina.py", line 413, in <module>
    periscope = main(args)
  File "/home/malago/miniconda3/envs/periscope/lib/python3.6/site-packages/periscope/scripts/search_for_sgRNA_illumina.py", line 368, in main
    canonical.write(args.sample+","+str(mapped_reads)+","+str(orfs_gRNA[orf])+","+orf+","+str(len(orfs[orf]))+","+str(orf_coverage[orf])+","+str(sgRPTL)+","+str(sgRPHT)+"\n")
KeyError: 'ORF7a'
[Fri Apr  8 08:15:17 2022]
Error in rule periscope:
    jobid: 3
    output: 6264_1_periscope_counts.csv, 6264_1_periscope_amplicons.csv, 6264_1_periscope_novel_counts.csv
    shell:
        python /home/malago/miniconda3/envs/periscope/lib/python3.6/site-packages/periscope/scripts/search_for_sgRNA_illumina.py --bam 6264_1.bam --score-cutoff 50 --output-prefix 6264_1 --score-cutoff 50 
--sample 6264_1_T0_NT_non_trattate --orf-bed /home/malago/softwares/periscope/periscope/resources/orf_start.bed --primer-bed /home/malago/softwares/periscope/periscope/resources/artic_primers_V3.bed 
--amplicon-bed /home/malago/softwares/periscope/periscope/resources/artic_amplicons_V3.bed --tmp /tmp --threads 24
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job periscope since they might be corrupted:
6264_1_periscope_counts.csv, 6264_1_periscope_novel_counts.csv
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/malago/GEN16-Covid_run_Negrar/6264_1_T0_NT_non_trattate/subsampled_421872_frgs/with_gRNA/.snakemake/log/2022-04-08T081438.024229.snakemake.log

```

### log's:
```
[Fri Apr  8 08:14:59 2022]
rule periscope:
    input: 6264_1.split.00.sam, 6264_1.bam, 6264_1.bam.bai
    output: 6264_1_periscope_counts.csv, 6264_1_periscope_amplicons.csv, 6264_1_periscope_novel_counts.csv
    jobid: 3

python /home/malago/miniconda3/envs/periscope/lib/python3.6/site-packages/periscope/scripts/search_for_sgRNA_illumina.py --bam 6264_1.bam --score-cutoff 50 --output-prefix 6264_1 --score-cutoff 50 --sample 6264_1_T0_NT_non_trattate --orf-bed /home/malago/softwares/periscope/periscope/resources/orf_start.bed --primer-bed /home/malago/softwares/periscope/periscope/resources/artic_primers_V3.bed --amplicon-bed /home/malago/softwares/periscope/periscope/resources/artic_amplicons_V3.bed --tmp /tmp --threads 24
[Fri Apr  8 08:15:17 2022]
Error in rule periscope:
    jobid: 3
    output: 6264_1_periscope_counts.csv, 6264_1_periscope_amplicons.csv, 6264_1_periscope_novel_counts.csv
    shell:
        python /home/malago/miniconda3/envs/periscope/lib/python3.6/site-packages/periscope/scripts/search_for_sgRNA_illumina.py --bam 6264_1.bam --score-cutoff 50 --output-prefix 6264_1 --score-cutoff 50 --sample 6264_1_T0_NT_non_trattate --orf-bed /home/malago/softwares/periscope/periscope/resources/orf_start.bed --primer-bed /home/malago/softwares/periscope/periscope/resources/artic_primers_V3.bed --amplicon-bed /home/malago/softwares/periscope/periscope/resources/artic_amplicons_V3.bed --tmp /tmp --threads 24
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job periscope since they might be corrupted:
6264_1_periscope_counts.csv, 6264_1_periscope_novel_counts.csv
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

**Comment by DrownedMala** [comment]
> Hello dear developers, since illumina's gRNA count-version was released, we tested it and got the error below from some samples. We are running periscope on data coming from duplicates, and it's returning this error only for one replicate at a time, while the other one runs flawlessly. Also, the same samples analyzed before this update ran without any issue; here I post the terminal's error output and, below that, the message contained in the snakemake.log.
> 
> Do you have any suggestion/idea about the nature of these errors? Thanks again for your tool and support! Simone
> ### Terminal's:
> 
> ```
> Traceback (most recent call last):
>   File "/home/malago/miniconda3/envs/periscope/lib/python3.6/site-packages/periscope/scripts/search_for_sgRNA_illumina.py", line 413, in <module>
>     periscope = main(args)
>   File "/home/malago/miniconda3/envs/periscope/lib/python3.6/site-packages/periscope/scripts/search_for_sgRNA_illumina.py", line 368, in main
>     canonical.write(args.sample+","+str(mapped_reads)+","+str(orfs_gRNA[orf])+","+orf+","+str(len(orfs[orf]))+","+str(orf_coverage[orf])+","+str(sgRPTL)+","+str(sgRPHT)+"\n")
> KeyError: 'ORF7a'
> [Fri Apr  8 08:15:17 2022]
> Error in rule periscope:
>     jobid: 3
>     output: 6264_1_periscope_counts.csv, 6264_1_periscope_amplicons.csv, 6264_1_periscope_novel_counts.csv
>     shell:
>         python /home/malago/miniconda3/envs/periscope/lib/python3.6/site-packages/periscope/scripts/search_for_sgRNA_illumina.py --bam 6264_1.bam --score-cutoff 50 --output-prefix 6264_1 --score-cutoff 50 
> --sample 6264_1_T0_NT_non_trattate --orf-bed /home/malago/softwares/periscope/periscope/resources/orf_start.bed --primer-bed /home/malago/softwares/periscope/periscope/resources/artic_primers_V3.bed 
> --amplicon-bed /home/malago/softwares/periscope/periscope/resources/artic_amplicons_V3.bed --tmp /tmp --threads 24
>         (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
> 
> Removing output files of failed job periscope since they might be corrupted:
> 6264_1_periscope_counts.csv, 6264_1_periscope_novel_counts.csv
> Shutting down, this might take some time.
> Exiting because a job execution failed. Look above for error message
> Complete log: /home/malago/GEN16-Covid_run_Negrar/6264_1_T0_NT_non_trattate/subsampled_421872_frgs/with_gRNA/.snakemake/log/2022-04-08T081438.024229.snakemake.log
> ```
> 
> ### log's:
> 
> ```
> [Fri Apr  8 08:14:59 2022]
> rule periscope:
>     input: 6264_1.split.00.sam, 6264_1.bam, 6264_1.bam.bai
>     output: 6264_1_periscope_counts.csv, 6264_1_periscope_amplicons.csv, 6264_1_periscope_novel_counts.csv
>     jobid: 3
> 
> python /home/malago/miniconda3/envs/periscope/lib/python3.6/site-packages/periscope/scripts/search_for_sgRNA_illumina.py --bam 6264_1.bam --score-cutoff 50 --output-prefix 6264_1 --score-cutoff 50 --sample 6264_1_T0_NT_non_trattate --orf-bed /home/malago/softwares/periscope/periscope/resources/orf_start.bed --primer-bed /home/malago/softwares/periscope/periscope/resources/artic_primers_V3.bed --amplicon-bed /home/malago/softwares/periscope/periscope/resources/artic_amplicons_V3.bed --tmp /tmp --threads 24
> [Fri Apr  8 08:15:17 2022]
> Error in rule periscope:
>     jobid: 3
>     output: 6264_1_periscope_counts.csv, 6264_1_periscope_amplicons.csv, 6264_1_periscope_novel_counts.csv
>     shell:
>         python /home/malago/miniconda3/envs/periscope/lib/python3.6/site-packages/periscope/scripts/search_for_sgRNA_illumina.py --bam 6264_1.bam --score-cutoff 50 --output-prefix 6264_1 --score-cutoff 50 --sample 6264_1_T0_NT_non_trattate --orf-bed /home/malago/softwares/periscope/periscope/resources/orf_start.bed --primer-bed /home/malago/softwares/periscope/periscope/resources/artic_primers_V3.bed --amplicon-bed /home/malago/softwares/periscope/periscope/resources/artic_amplicons_V3.bed --tmp /tmp --threads 24
>         (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
> 
> Removing output files of failed job periscope since they might be corrupted:
> 6264_1_periscope_counts.csv, 6264_1_periscope_novel_counts.csv
> Shutting down, this might take some time.
> Exiting because a job execution failed. Look above for error message
> ```

Hello again,
If it can be helpful, I might share those error-causing FASTQs with you; for any other information you might need, just let me know!
Thanks in advance,
Regards,
Simone

**Comment by mbdabrowska1** [comment]
Does it always happen for ORF7a or various ORFs?

**Comment by DrownedMala** [comment]
Such errors are reported only for ORF7a

edit: ORF7 -> ORF7a

**Comment by mbdabrowska1** [comment]
I think the issue might be that there are only sgRNA reads for ORF7a in this sample, and no gRNA reads. This would cause the dictionary to miss the ORF7a key for gRNA and result in this error. I will look into a fix now and see if it solves the problem.

**Comment by mbdabrowska1** [comment]
I released the fix now, let me know if it fixes your problem. If it doesn't I will look into other possibilities on what might be causing the issue.

**Comment by DrownedMala** [comment]
Thanks for the work, but it's still producing the same error unfortunately

**Comment by mbdabrowska1** [comment]
What did the results look like for ORF7a before the update?

**Comment by DrownedMala** [comment]
I didn't keep logs for the previous version of periscope since it worked just fine, but I can post the outputs (of the precedent version) of a sample which causes the error when analyzed with the updated version.

Here <_periscope_counts.csv> output:
`sample,mapped_reads,orf,sgRNA_count,coverage,sgRPTL,sgRPHT
6264_1_T0_NT_non_trattate,819689,S,303,1480.0,204.72972972972974,36.965239255376126
6264_1_T0_NT_non_trattate,819689,ORF7a,2,7869.0,0.25416190113102044,0.24399497858334077
6264_1_T0_NT_non_trattate,819689,ORF6,59,4084.0,14.446620959843292,7.197851868208552
6264_1_T0_NT_non_trattate,819689,N,415,7146.0,58.07444724321299,50.62895805604321
6264_1_T0_NT_non_trattate,819689,M,282,5411.0,52.11605987802625,34.40329198025105
6264_1_T0_NT_non_trattate,819689,ORF3a,10,3684.0,2.7144408251900107,1.2199748929167038
6264_1_T0_NT_non_trattate,819689,E,22,1392.0,15.804597701149426,2.6839447644167485`

Here the <_periscope_novel_counts.csv> output:
`sample,mapped_reads,orf,sgRNA_count,coverage,sgRPTL,sgRPHT
6264_1_T0_NT_non_trattate,819689,novel_21510,1,1479.0,0.676132521974307,0.12199748929167038
6264_1_T0_NT_non_trattate,819689,novel_13674,1,5426.0,0.18429782528566163,0.12199748929167038
6264_1_T0_NT_non_trattate,819689,novel_10639,3,4377.0,0.6854009595613434,0.36599246787501116
6264_1_T0_NT_non_trattate,819689,novel_247,1,1813.0,0.5515719801434087,0.12199748929167038
6264_1_T0_NT_non_trattate,819689,novel_26497,4,5405.0,0.7400555041628122,0.48798995716668153
6264_1_T0_NT_non_trattate,819689,novel_22281,15,3248.0,4.6182266009852215,1.8299623393750557
`
If you need some more information, just ask!
And thanks again for the help,
Simone

**Comment by mbdabrowska1** [comment]
And can i just double check what you mean by this:

> We are running periscope on data coming from duplicates, and it's returning this error only for one replicate at a time, while the other one runs flawlessly.

Do you mean that you tried running it multiple times on the same pair of datasets and only one of them throws an error but its not always the same one of the pair?

**Comment by DrownedMala** [comment]
We have ten samples, for each sample we have two technical replicates. The software throws an error in 3 out of 10 samples and only in one replicate for each one of them

**Comment by mbdabrowska1** [comment]
Hmm I cannot think of any other reason this updated code would fail, other than there are no ORF7a counts for gRNA, but there are ORF7a counts for sgRNA. Are you certain you re-ran your data on the fixed version 0.1.2, which corrects for that? To double check the version of periscope in your environment you can activate the env and run `conda list`

**Comment by DrownedMala** [comment]
Ok, yes, v0.1.2 works just fine, I was the one not working: apparently, I only downloaded the updated version, but did not apply it.

Now it runs,
Thanks a lot for the support!
Simone

**Comment by mbdabrowska1** [comment]
Great, happy its now working!
